### ISSUE TITLE
GitHubまたはF-droid上でapkを公開して欲しい。

### ISSUE THREAD

**Issue by reindex-ot** [geckour/NowPlaying4GPM#88]
GooglePlay上からアプリをインストールできなくなっていました。apkをダウンロードできるようにGitHubかF-droid上に公開をしていただきたいです。

**Comment by Ricotan-Linus** [comment]
In my opinion, You should be get from apk archive site.

**Comment by geckour** [comment]
[新アプリ](https://play.google.com/store/apps/details?id=com.geckour.nowplaying4droid)として再リリースしたので close します
