### ISSUE TITLE
MushroomActivityのIntent-Filterに CATEGORY_DEFAULT を追加してほしい

### ISSUE THREAD

**Issue by tateisu** [geckour/NowPlaying4GPM#95]
SubwayTooterというMastodonクライアントを作っている者です。
Simejiマッシュルームプラグインを呼び出す機能があります。

最近ユーザから問い合わせがあってNowPlaying4Droidを呼び出せない状態なのが分かりました。
調べてみると下記のように呼び出される側に CATEGORY_DEFAULT の指定が必要らしいので、追加していただけないでしょうか。

https://developer.android.com/guide/topics/manifest/category-element
> Note: In order to receive implicit intents, you must include the [CATEGORY_DEFAULT](https://developer.android.com/reference/android/content/Intent#CATEGORY_DEFAULT) category in the intent filter. The methods [startActivity()](https://developer.android.com/reference/android/app/Activity#startActivity(android.content.Intent)) and [startActivityForResult()](https://developer.android.com/reference/android/app/Activity#startActivityForResult(android.content.Intent,%20int)) treat all intents as if they declared the [CATEGORY_DEFAULT](https://developer.android.com/reference/android/content/Intent#CATEGORY_DEFAULT) category. If you do not declare it in your intent filter, no implicit intents will resolve to your activity.

https://medium.com/androiddevelopers/making-sense-of-intent-filters-in-android-13-8f6656903dde

**Comment by tateisu** [comment]
現象を確認した端末
Android12 Sony XQ-BT44

**Comment by geckour** [comment]
ご迷惑をおかけしています、ご報告ありがとうございます！
先程審査に出した v3.1.1 にて修正しましたので close させていただきます 🙏

**Comment by tateisu** [comment]
ありがとうございます！
